version: "3.2"
services:
  db:
    build: .
    image: mongo:4.2
    container_name: db
    volumes:
      - ./data:/data/db
    restart: always
    ports: 
      - 27017:27017
    environment: 
      MONGODB_URI: ${MONGODB_URI}